name: Pull Request Build

on:
    pull_request:
        branches: ["main"]

jobs:
    build-library:
        name: Build Library
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install Dependencies
              run: npm install

            - name: Build plugin
              run: npm run build

    verify-changelog:
        name: Verify Changelog
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Changelog Reader
              uses: mindsers/changelog-reader-action@v2.2.0
              with:
                  # Path to the CHANGELOG file containing the log entries
                  path: ./CHANGELOG.md
                  # Specifies if the CHANGELOG.md file should be validated and the behavior of the action
                  validation_level: error
